### PR TITLE
53 Modal Design

### PR DESCRIPTION
**Pull request by Felix-by-merkle**
**53**

**About**
Refactor modal 

**Changes**
One react modal only that renders the content for the CRUD actions

**Testing**
N/a

**Screenshot / Gifs**
N/a

**Notes**
n/a

### CODE REVIEW

**Review by antonio-rodrigues — APPROVED** [review]
Looks good to me

**Comment by JWebCoder** [comment]
[Modal redesign](https://trello.com/c/jeas7Fpw/53-modal-redesign)

**Review by JWebCoder — CHANGES_REQUESTED** [review]
please check figma on the margins and overall modal design.

**Comment by miriampereira** [comment]
Please proceed fixing the next changes:
- use the font family required: ProximaNova
- the title "Add component" should be black
- "Friendly name" text and the input should be aligned as a column
- text input for the component name should be full width as the select input (fix the input styles)
- add horizontal padding to the action btns (add component and cancel)
- Fix the width of the modal to be similar to the mockups

**Review by miriampereira — CHANGES_REQUESTED** [review]
Please proceed fixing the next changes:

use the font family required: ProximaNova
the title "Add component" should be black
"Friendly name" text and the input should be aligned as a column
text input for the component name should be full width as the select input (fix the input styles)
add horizontal padding to the action btns (add component and cancel)
Fix the width of the modal to be similar to the mockups

**Comment by Felix-by-merkle** [comment]
> Please proceed fixing the next changes:
> 
> * use the font family required: ProximaNova
> * the title "Add component" should be black
> * "Friendly name" text and the input should be aligned as a column
> * text input for the component name should be full width as the select input (fix the input styles)
> * add horizontal padding to the action btns (add component and cancel)
> * fix the width of the modal to be similar to the mockups

Everything related to form inputs will be dealt in another ticket(https://trello.com/c/Bw8RUBVr/58-forms)

**Review by miriampereira — APPROVED** [review]

**Pull request merged**
