### PR TITLE
Search functionality for component tree

### PR DESCRIPTION
**Pull request by Felix-by-merkle**
**##51#**

**About**
Search functionality to filter the component tree by friendly name

**Changes**
- Add logic for the search function
- Added 2 new props to component model to enable the control of css classes and states
- Nested components will be shown inside the expanded parent component
- Highlighted results

**Testing**
Use the search input and button to search by for a component by its friendly name

**Screenshot / Gifs**
N/a

**Notes**
Enabling the search by typing is possible, different highlight is a WIP

### CODE REVIEW

**Comment by bmirra01** [comment]
@Felix-by-merkle, I think the search issue you mentioned with the input component still persists, after a search, and if I clear it, I get the same result, like the state didn't changed.

**Comment by Felix-by-merkle** [comment]
I'll revert to the old input

**Review by bmirra01 — APPROVED** [review]
Looks fine now, the search is working as intended

**Review by antonio-rodrigues — APPROVED** [review]
Looking good, works as intended

**Pull request merged**
